Fix pickle with lambda and non-top function failure
Current attribute value list with same value will cause
cache pickle failure. To fix the pickle failure, need
update few functions to top of module.

Current factory local lambda object will fail with pickle:

AttributeError: Can't pickle local object
'MappedAggregationCollection.factory.<locals>.<lambda>'

move the lambda to a callable class on top level of the module,
then it should bypass pickle.

Also need move creator_factory to callable class on top of
module. The owning_class in the callable class need be updated
and make sure not None, so update __get__ to set self.creator
also when update owning_class.

Also get rid of duplicate value from value list for current
usage.

Update on attribute module with the creator function, replace the
function with callable class to avoid the pickle bug.

Signed-off-by: Wayne Sun <gsun@redhat.com>